name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Package Setup
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install -v -e .[dev]

      - name: Build Python Package
        run: |
          python -m hatch build

      - name: Store Python Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/cortile*

  pypi-test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi-test
      url: https://test.pypi.org/p/cortile
    permissions:
      id-token: write
    steps:
      - name: Download Python Artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
